name: CI
on:
  push:
    paths:
      - 'src/**'   
      - '.github/workflows/**'   
  pull_request:
jobs:
  build:
    if: ${{ false }} # disable for now
    runs-on: ubuntu-latest
    env:
      SLN_FILE_NAME: Digitalroot.Valheim.Common.Utils.sln
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.1
        with:
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
      - name: Restore packages
        run: dotnet restore src/${{ env.SLN_FILE_NAME }} --nologo
      - name: Build
        run: dotnet build src/${{ env.SLN_FILE_NAME }} -c Release --no-restore --nologo
      - name: Test
        run: dotnet test src/${{ env.SLN_FILE_NAME }} -c Release --no-build -l "trx;LogFileName=test-results.trx" --nologo
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: ./src/UnitTests/TestResults/test-results.trx
          name: test-results
          retention-days: 1
